language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '8'
  - '7'
  - '6'
  - '4'
before_script:
  - npm prune
after_success:
  - npm run coverage:report
  - npm run semantic-release
script:
  - npm run coverage
  - npm run coverage:check
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
